/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fact.h"
int factorial(int a)
{
	if(a==0)
	return 1;
	else
	return a*factorial(a-1);
}
int *
fact_1_svc(intpair *argp, struct svc_req *rqstp)
{
	static int  result;

	int a,res;
	a=argp->a;
	res=factorial(a);
	result=res;

	return &result;
}
