/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "pali.h"


void
str_prog_1(char *host)
{
	CLIENT *clnt;
	char **result_1;
	strpair  pali_1_arg;
	char **result_2;
	strpair  rev_1_arg;
         int ch;

#ifndef	DEBUG
	clnt = clnt_create (host, STR_PROG, STR_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
          
       do
       {
         printf("\nenter choice\n1.pali\n2.rev\n3.exit ");
         scanf("%d",&ch);

       switch(ch)
       {
     
        case 1:
         printf("enter string ");
         scanf(" %s", pali_1_arg.a);
        result_1 = pali_1(&pali_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
         else
          {
           if(strcmp(*result_1,"yes")!=0)
            printf("\n string isnot palindrome");
 
           else
            printf("\n string is palindrome");
          }

           printf("\n anser= %s",*result_1);
        break;

        case 2:
         printf("\n enter string");
         scanf(" %s", rev_1_arg.a);
	result_2 = rev_1(&rev_1_arg, clnt);
	if (result_2 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
        else
         printf("reversed string= %s",*result_2);
        break;

       }
  }while(ch!=3);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	str_prog_1 (host);
exit (0);
}
